// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/22/2026, 11:19:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/plugins/**/*.{js,ts,mjs}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/composables/**/*.{js,ts,mjs}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/utils/**/*.{js,ts,mjs}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/app.config.{js,ts,mjs}","/Users/oniolajumoke/Documents/fin/finapp/financelandingpage/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;